Implement docker-compose
asiday/news-aggregator pull request #31
Opened 2022-04-11 12:50 UTC by asiday

Changes:
-Change the link for scheduled task in crawler to "country=ch"
-Create docker-compose.yml file with crowler and mariadb
-Create appropriate schema for creating new db
-Add to docker-compose.yml file service.
-Save key as secret in docker-compose.yml

Close#17

2022-04-13 07:58 UTC, yambay requested changes

2022-04-13 07:58 UTC, yambay commented on README.md
> +  + requested json files are saved in mariadb
Do you really save JSON files in the database? Or maybe from JSON converted entities?

2022-04-13 07:58 UTC, yambay commented on README.md
> +  + get rows from existing mariadb
Get entities. Rows sound too simple

2022-04-13 07:58 UTC, yambay commented on README.md
> ++ Save all sensitive information such as api key in .env file
Please, describe which parameters one should put into '''.env''' file.

2022-04-13 07:58 UTC, yambay commented on README.md
> ++ Save all sensitive information such as api key in .env file
Maybe an example of an .env file would be good at this point

2022-04-13 07:58 UTC, yambay commented on crawler/src/main/java/dev/asida/crawler/schedule/ScheduledTask.java
> +        //r.getLanguages().add(Language.RUSSIAN);
Why do you leave commented code here? Please remove

2022-04-13 07:58 UTC, yambay commented on crawler/src/main/resources/schema.sql
>  );
Do you need this SQL file here? You moved it into news-aggreagator/scripts, so please remove it from here (or move into test if neccesary)

2022-04-13 07:58 UTC, yambay commented on crawler/src/test/java/dev/asida/crawler/schedule/ScheduledTaskTest.java
> +        //r.getLanguages().add(Language.GERMAN);
Remove commented code

2022-04-13 07:58 UTC, yambay commented on docker-compose.yml
> +      SPRING_DATASOURCE_URL: jdbc:mysql://app_db:3306/news_aggregator
The database name is already defined as "${MARIADB_DATABASE}", so there is no need to hard code the database name in the data source url. Please use something like 

jdbc:mysql://app_db:3306/${MARIADB_DATABASE}

2022-04-13 07:58 UTC, yambay commented on docker-compose.yml
> +      SPRING_DATASOURCE_URL: jdbc:mysql://app_db:3306/news_aggregator
Use ${MARIADB_DATABASE} instead of hard coded DB name

2022-04-13 07:58 UTC, yambay commented on docker-compose.yml
> +    ports:
I don't think, that this image should expose any ports. Please, try to remove this ports mapping and test if your applications still work.

2022-04-13 07:58 UTC, yambay commented on service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS articles (
Do you need this SQL file here? You moved it into news-aggreagator/scripts, so please remove it from here (or move into test if neccesary)

2022-04-13 07:59 UTC, yambay commented
By the way. Your commit message starts with "Implement docker-compose". Are you sure, that you implement docker-compose? Or maybe you just make use of docker-compose to start your application?

2022-04-13 09:19 UTC, asiday commented on README.md
> +  + requested json files are saved in mariadb
Of course "JSON converted entities"

2022-04-13 09:22 UTC, asiday commented on README.md
> +  + get rows from existing mariadb
Done.

2022-04-13 09:23 UTC, asiday commented on README.md
> ++ Save all sensitive information such as api key in .env file
Examples are added.

2022-04-13 09:25 UTC, asiday commented on crawler/src/main/java/dev/asida/crawler/schedule/ScheduledTask.java
> +        //r.getLanguages().add(Language.RUSSIAN);
Removed.

2022-04-13 09:52 UTC, asiday commented on crawler/src/test/java/dev/asida/crawler/schedule/ScheduledTaskTest.java
> +        //r.getLanguages().add(Language.GERMAN);
Done

2022-04-13 09:57 UTC, asiday commented on docker-compose.yml
> +      SPRING_DATASOURCE_URL: jdbc:mysql://app_db:3306/news_aggregator
The URL changed using placeholder.

2022-04-13 09:58 UTC, asiday commented on docker-compose.yml
> +      SPRING_DATASOURCE_URL: jdbc:mysql://app_db:3306/news_aggregator
Done.

2022-04-13 10:05 UTC, asiday commented on docker-compose.yml
> +    ports:
After removing ports mapping, the app is still working.

2022-04-13 10:06 UTC, asiday commented on service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS articles (
Tried to remove. Unfortunately it is not working.

2022-04-13 11:31 UTC, yambay approved these changes

2022-04-14 08:48 UTC, asiday commented on crawler/src/main/resources/schema.sql
>  );
The schema.sql file is used by Spring Data under the hood.

2022-04-14 08:49 UTC, merged