Implement crawler.
asiday/news-aggregator pull request #32
Opened 2022-04-28 15:40 UTC by asiday

Changes:
- Delete auto generation of primary key.
- Create a unique ID for each article.

Close #22

2022-04-29 07:50 UTC, yambay requested changes

2022-04-29 07:50 UTC, yambay commented on crawler/src/test/java/dev/asida/crawler/services/NewsServiceTest.java
> +    @Disabled
This isn't so good idea. Please, use mocked service instead of real one and enable this tests again.

2022-04-29 07:50 UTC, yambay commented on crawler/src/main/java/dev/asida/crawler/schedule/ScheduledTask.java
> +        articles.forEach(article -> article.setId( (article.hashCode()& 0x7fffffff)));
Too many SKOBKI

2022-04-29 14:25 UTC, asiday commented on crawler/src/main/java/dev/asida/crawler/schedule/ScheduledTask.java
> +        articles.forEach(article -> article.setId( (article.hashCode()& 0x7fffffff)));
Unnecessary brackets are removed.

2022-05-05 07:56 UTC, yambay approved these changes

2022-05-05 08:06 UTC, merged